# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://rosenrose.github.io"
baseurl: ""
#nasurl: "http://crazytempler.ipdisk.co.kr:81/publist/HDD1/Public/doujin"

imgserver1: "https://d2l1b145ht03q6.cloudfront.net"
imgserver2: "https://d2mc8yflsr3zqe.cloudfront.net"
imgserver3: "https://dxpc2233q2b6a.cloudfront.net"
imgserver4: "https://franch122.s3.amazonaws.com/doujin"
imgserver5: "https://kjw122.s3.amazonaws.com/doujin"
imgserver6: "https://franch122hanmail2.s3.amazonaws.com/doujin"
imgserver7: "https://franch122paran.s3.amazonaws.com/doujin"
imgserver8: "https://franch122tistory.s3.amazonaws.com/doujin"
imgserver9: "https://kjw4569-2.s3.amazonaws.com/doujin"
imgserver10: "https://rosentemplerdaum.s3.amazonaws.com/doujin"
imgserver11: "https://rosentemplerhanmail.s3.amazonaws.com/doujin"
imgserver12: "https://rosentemplerhanmail2.s3.amazonaws.com/doujin"

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: "Touhou Doujin"

# Short description of your site
description: "동방 동인지"

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  전체 검색: "fsearch"
  제목 검색: "qsearch"
  태그: "tags"
  랜덤 페이지: "randompage"
  랜덤 리스트: "randomlist"  
  이 곳은?: "aboutus"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/reimu.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#607d8b"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#263238"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: rosenrose
  
# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: "noname@email.com"
#  facebook: daattali
#  github: daattali
#  twitter: daattali
#  reddit: yourname
#  google-plus: +DeanAttali
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
#  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
#url-pretty: "MyWebsite.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "UA-137254721-1"

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "rosenrose"

# To use Facebook Comments, fill in a Facebook App ID
# fb_comment_id: ""

# --- Misc --- #

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Asia/Seoul"
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 10
encoding: utf-8
kramdown:
  input: GFM
# Default YAML values (more information on Jekyll's site)
collections:
  tags:
    output: true
    permalink: /tags/:path/
  
defaults:
  -
    scope:
      path: ''
      type: tags
    values:
      layout: tag
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - restore.txt
  - /test

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap

search_provider: "google"
google:
  search_engine_id: "009745835481055354123:n-gyosnz6cu"

future: true
# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
